# Lex CMake module for processing .l files

function(add_lex_source target_name lex_file)
    # Get the base name without extension
    get_filename_component(base_name ${lex_file} NAME_WE)
    
    # Set output file name with lexer prefix to avoid conflicts with yacc
    set(c_file "${CMAKE_CURRENT_BINARY_DIR}/${base_name}_lex.c")
    
    # Set output header file name
    set(h_file "${CMAKE_CURRENT_BINARY_DIR}/${base_name}_lex.h")
    
    # Create custom target to generate .c and .h files from .l file
    add_custom_target(${base_name}_lex
        COMMAND lex --header-file=${h_file} -o ${c_file} ${CMAKE_CURRENT_SOURCE_DIR}/${lex_file}
        BYPRODUCTS ${c_file} ${h_file}
        DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${lex_file}
        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
        COMMENT "Generating lexer from ${lex_file}"
        VERBATIM
    )
    
    # Create a dummy source file that will be replaced
    file(WRITE ${c_file} "// Generated by lex\n")
    
    # Add generated file to target sources
    target_sources(${target_name} PRIVATE ${c_file})
    
    # Make target depend on the lex generation
    add_dependencies(${target_name} ${base_name}_lex)
endfunction()
